#!/usr/bin/env python3
"""
BIDS Knowledge Base Retriever (JSONL-based).

Drop-in replacement for the original txt/md keyword Retriever. Loads the
structured knowledge base generated by extract_kb.py (knowledge.jsonl,
relationships.jsonl, sources.jsonl) once at construction and serves
repeated queries from an in-memory index.

Public API (unchanged):
    retriever = Retriever("./knowledge")          # data_dir with the JSONL files
    result = retriever.retrieve("What is the task entity?", top_k=2)
    # result is always a formatted string -> passed to the LLM by the Planner

Architecture:
    User Query -> Planner -> Retriever.retrieve(query, top_k) -> LLM

Design notes:
  * Zero external dependencies (Python stdlib only).
  * Loading/parsing, indexing, scoring and formatting are kept in separate
    classes so the token scorer can later be swapped for embeddings.
  * All weights/fields are derived from the ACTUAL schema of the generated
    knowledge base (verified against knowledge.jsonl in this directory).
"""

import json
import logging
import math
import os
import re
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

logger = logging.getLogger(__name__)

# Knowledge base file names (relative to data_dir)
KNOWLEDGE_FILE = "knowledge.jsonl"
RELATIONSHIPS_FILE = "relationships.jsonl"
SOURCES_FILE = "sources.jsonl"
REPORT_FILE = "processing_report.json"  # never used as retrieval content

# Written by the enrichment pass: the same records carrying an "ai_enrichment"
# block that explains what a rule means, why it matters and how to resolve it.
# Merged onto the base records by id when present, so enrichment is additive and
# a knowledge base without this file behaves exactly as before.
ENRICHED_FILE = "enriched_knowledge.jsonl"

# Fallback messages (stable strings, asserted by tests)
MSG_NO_KB = "Knowledge base file 'knowledge.jsonl' not found in {}."
MSG_EMPTY_KB = "The BIDS knowledge base is empty or could not be loaded."
MSG_EMPTY_QUERY = "An empty query was provided."
MSG_NO_MATCH = 'No relevant BIDS knowledge found for the query: "{}".'

# Queries whose best score falls below this (for a large KB) are treated
# as having no real match, avoiding boilerplate-driven noise for
# out-of-KB terms such as "Funding" or "SourceDatasets". The floor scales
# down with KB size so small knowledge bases still return real matches.
MIN_BEST_SCORE = 6.0


# ====================================================================
# Data model
# ====================================================================


class KnowledgeRecord:
    """
    One record from knowledge.jsonl.

    Maps the real top-level fields of the generated knowledge base:
        id, knowledge_type, title, summary, retrieval_text, scope,
        source, raw_content, bids_version, schema_version, and the
        optional rule fields: requirements, conditions, allowed_values,
        severity, expression, unit.
    """

    __slots__ = (
        "id", "knowledge_type", "title", "summary", "retrieval_text",
        "source", "scope", "raw_content", "bids_version", "schema_version",
        "requirements", "conditions", "allowed_values",
        "severity", "expression", "unit", "enrichment",
    )

    def __init__(self, data: Dict[str, Any]) -> None:
        self.id: str = str(data.get("id", "") or "")
        self.knowledge_type: str = str(data.get("knowledge_type", "unknown"))
        self.title: str = str(data.get("title", "") or "")
        self.summary: str = str(data.get("summary", "") or "")
        self.retrieval_text: str = str(data.get("retrieval_text", "") or "")
        self.source: Dict[str, Any] = data.get("source") or {}
        self.scope: Dict[str, Any] = data.get("scope") or {}
        self.raw_content: Any = data.get("raw_content")
        self.bids_version: str = str(data.get("bids_version", "") or "")
        self.schema_version: str = str(data.get("schema_version", "") or "")
        self.requirements: Any = data.get("requirements")
        self.conditions: Any = data.get("conditions")
        self.allowed_values: Any = data.get("allowed_values")
        self.severity: Any = data.get("severity")
        self.expression: Any = data.get("expression")
        self.unit: Any = data.get("unit")
        self.enrichment: Dict[str, Any] = data.get("ai_enrichment") or {}

    # -- searchable representation ------------------------------------

    def build_search_blocks(self) -> List[Tuple[str, str, float]]:
        """
        Build the searchable representation of this record as a list of
        ``(label, text, weight)`` tuples.

        Weights reflect how discriminating each field is:
        * identifiers (id) and scope constraints are the most specific;
        * free-text descriptions are the least specific.
        """
        blocks: List[Tuple[str, str, float]] = []

        def add(label: str, text: Any, weight: float) -> None:
            text = self._normalize(text)
            if text:
                blocks.append((label, text, weight))

        add("id", self.id, 4.0)
        add("title", self.title, 3.0)
        add("scope", self._flatten(self.scope), 3.0)
        add("requirements", self._flatten(self.requirements), 2.5)
        add("allowed_values", self._flatten(self.allowed_values), 2.0)
        add("conditions", self._flatten(self.conditions), 2.0)
        add("summary", self.summary, 1.5)
        add("retrieval", self.retrieval_text, 1.5)
        add("expression", self.expression, 1.5)
        add("severity", self.severity, 1.0)
        add("unit", self.unit, 1.0)

        # Enrichment text describes the same rule in the words a user would
        # reach for ("my file is not 3D", "how do I fix"), which the schema's own
        # phrasing never contains. Weighted below the identifiers so it widens
        # what can be found without displacing an exact identifier match.
        #
        # It is ONE block, not one per field, even though that loses the ability
        # to weight the parts differently. Scoring adds a token's contribution
        # once per block it appears in, and an explanation naturally repeats its
        # subject across description, causes and resolution, so five blocks
        # multiplied a single word by five. That was enough to rank an explained
        # validation check above the definition of the very field a user had
        # asked about by name.
        if self.enrichment:
            add(
                "explanation",
                " ".join(
                    part for part in (
                        self._normalize(self.enrichment.get("description")),
                        self._normalize(self.enrichment.get("why_it_matters")),
                        self._flatten(self.enrichment.get("common_causes")),
                        self._flatten(self.enrichment.get("resolution_guidance")),
                        self._flatten(self.enrichment.get("example_scenarios")),
                    ) if part
                ),
                1.2,
            )

        add("raw_content", json.dumps(self.raw_content, ensure_ascii=False), 0.8)

        return blocks

    def identity_text(self) -> str:
        """Compact text of the most identity-bearing fields (id/title/scope)."""
        return self._normalize(" ".join([
            self.id,
            self.title,
            self._flatten(self.scope),
        ]))

    # -- helpers --------------------------------------------------------

    @staticmethod
    def _normalize(text: Any) -> str:
        """Lowercase and treat '_' as a word separator (BIDS ids use it)."""
        return re.sub(r"[^a-z0-9 ]", " ", str(text or "").lower())

    @classmethod
    def _flatten(cls, value: Any) -> str:
        """Serialize arbitrary JSON values into a flat searchable string."""
        if value is None:
            return ""
        if isinstance(value, str):
            return value
        if isinstance(value, dict):
            return " ".join(
                f"{k}: {cls._flatten(v)}" for k, v in value.items()
            )
        if isinstance(value, (list, tuple)):
            return " ".join(cls._flatten(v) for v in value)
        return str(value)


class RelationshipEdge:
    """One edge from relationships.jsonl."""

    __slots__ = ("source", "relation", "target", "source_reference", "confidence")

    def __init__(self, data: Dict[str, Any]) -> None:
        self.source: str = str(data.get("source", "") or "")
        self.relation: str = str(data.get("relation", "") or "")
        self.target: str = str(data.get("target", "") or "")
        self.source_reference: str = str(data.get("source_reference", "") or "")
        self.confidence: str = str(data.get("confidence", "explicit"))


# ====================================================================
# Scorer — lightweight token scoring with field-aware weights
# ====================================================================


class Scorer:
    """
    Token-level scorer.

    Rules:
    * Query is tokenized (lowercase, punctuation and '_' are separators,
      stop words removed).
    * A whole-word token match inside a block adds ``2.0 * block_weight``.
    * If a token has no whole-word match anywhere, a prefix match (token
      is a word prefix, length >= 3) adds ``0.5 * block_weight``.
    * Known BIDS identifiers (task, sub, bold, ...) get a flat bonus when
      they appear in the record's identity (id/title/scope).
    * If the whole normalized query appears verbatim in title/summary/
      retrieval_text, a phrase bonus is added.

    Whole-word matching avoids the "every record scores similarly because
    of common words" problem: stop words are excluded and partial/substring
    matches are not rewarded across every record.

    Two damping rules keep a single lucky word from carrying a record: the
    rarity multiplier is capped, and a multi-word query whose match rests on one
    token is penalised. Both exist because explanatory text uses ordinary
    English, which introduces many words that are rare in the knowledge base
    while saying nothing about what a record is for.
    """

    # Ceiling on the rarity multiplier for a single token.
    MAX_IDF = 3.0

    # Queries at least this long must match more than one token to score fully.
    # Below it, a query is usually an identifier or a code and one match is the
    # whole question.
    COVERAGE_MIN_TOKENS = 3

    # What a multi-word query's score is multiplied by when only one token hit.
    SINGLE_MATCH_PENALTY = 0.35

    # Shortest query token allowed to match as a word prefix. Also the length of
    # the prefix keys in the retriever's postings lists, so the two must agree:
    # a shorter prefix rule than the index would silently stop finding matches.
    MIN_PREFIX_LEN = 3

    STOPWORDS = frozenset({
        "a", "an", "the", "and", "or", "but", "if", "then", "else",
        "in", "on", "at", "to", "of", "for", "with", "by", "from",
        "is", "are", "was", "were", "be", "been", "being", "it", "its",
        "this", "that", "these", "those", "as", "not", "do", "does",
        "did", "will", "would", "may", "might", "should", "shall",
        "what", "which", "who", "whom", "whose", "why", "how",
        "when", "where", "there", "here", "have", "has", "had",
        "can", "could", "than", "then", "so", "up", "out", "about",
        "into", "within", "without", "under", "over", "between",
        "after", "before", "during", "while", "such", "some", "any",
        "all", "each", "other", "please", "about", "give", "use",
        # Low-information modals / generic JSON-schema vocabulary that
        # would otherwise give near-equal scores to many records.
        "must", "can", "could", "might", "need", "needs", "shall",
        "contains", "containing", "item", "items", "array", "arrays",
        "placeholder", "todo", "value", "values", "list", "lists",
        "string", "boolean", "integer", "number", "numbers",
        "field", "fields", "type", "types", "key", "keys",
        "named", "called", "present", "absent",
        "contain", "include", "includes", "including", "specify",
        "specifies", "specified", "used", "uses", "using", "needed",
        "mean", "means", "make", "makes", "look", "looks",
        # Personal pronouns and conversational filler. A user asking for help
        # writes "how do I fix my dataset", and without these the single-letter
        # pronoun "i" scores a whole-word match against the schema's "i" enum,
        # which is the imaginary part of a complex image. The top hit for the
        # most natural phrasing of a help request was therefore an unrelated
        # record, purely because of the word "I".
        "i", "me", "my", "mine", "myself",
        "we", "us", "our", "ours", "you", "your", "yours",
        "he", "him", "his", "she", "her", "hers", "they", "them", "their",
        "am", "get", "gets", "got", "want", "wants", "help", "tell",
        "say", "says", "said", "know", "think", "try", "trying",
    })

    # BIDS-specific terms that deserve an identity bonus when matched.
    # '_' is a word separator, so write tokens without underscores.
    BIDS_TERMS = frozenset({
        "sub", "ses", "subject", "session", "task", "acq", "acquisition",
        "run", "space", "desc", "suffix", "extension", "datatype",
        "modality", "bold", "events", "participant", "tsv", "json",
        "nii", "gz", "dataset", "anat", "func", "dwi", "fmap", "perf",
        "eeg", "meg", "ieeg", "pet", "mrs", "micr", "beh", "nirs",
        "motion", "t1w", "t2w", "cbf", "sbref", "echo", "flip", "dir",
        "inv", "hemi", "label", "fieldmap", "channels", "electrodes",
        "physio", "phenotype", "template", "entity", "sourcedata",
        "derivatives", "code", "stimuli", "sessions", "field",
        "metadata", "recommended", "required", "optional",
    })

    # whole-word / prefix matching against normalized (lowercased) text
    _WORD_RE = re.compile(r"\b[a-z0-9]+\b")

    @classmethod
    def tokenize(cls, text: str) -> List[str]:
        return [
            t for t in cls._WORD_RE.findall(KnowledgeRecord._normalize(text))
            if t not in cls.STOPWORDS
        ]

    @classmethod
    def score(
        cls,
        query: str,
        record: KnowledgeRecord,
        blocks: List[Tuple[str, str, float]],
        identity_text: str,
        idf_map: Optional[Dict[str, float]] = None,
    ) -> float:
        if not query or not query.strip():
            return 0.0

        tokens = cls.tokenize(query)
        if not tokens:
            return 0.0

        idf_map = idf_map or {}
        total = 0.0
        matched_tokens = 0

        # 1. Phrase bonus: whole normalized query appears verbatim.
        norm_query = re.sub(r"\s+", " ", query.lower()).strip()
        phrase_text = " ".join([
            record.title, record.summary, record.retrieval_text,
        ]).lower()
        if norm_query and norm_query in phrase_text:
            total += 5.0

        # 2. Token matches per block.
        for token in tokens:
            variants = cls._match_variants(token)

            # Rarity is informative but must not be decisive on its own. An
            # uncapped multiplier lets ONE incidental word carry a record over
            # the relevance floor: an unrelated question containing "configure"
            # matched a record whose explanatory text happened to use that word,
            # and scored four times the threshold on that single hit. The cap
            # keeps rare terms ahead of common ones without letting one of them
            # outvote everything else.
            idf = min(idf_map.get(token, 1.0), cls.MAX_IDF)

            whole_match_any = False
            for _label, text, weight in blocks:
                if any(cls._whole_word(v, text) for v in variants):
                    total += 2.0 * weight * idf
                    whole_match_any = True
            if not whole_match_any and len(token) >= cls.MIN_PREFIX_LEN:
                for _label, text, weight in blocks:
                    if cls._prefix_word(token, text):
                        total += 0.5 * weight * idf
                        whole_match_any = True
                        break
            if whole_match_any:
                matched_tokens += 1
            # 3. BIDS identifier bonus (also damped by term rarity).
            if token in cls.BIDS_TERMS and cls._whole_word(token, identity_text):
                total += 3.0 * min(idf, 1.5)

        # 3. Coverage requirement.
        #
        # A record that answers one word of a six-word question has not answered
        # the question. Requiring a second matched token for anything but a very
        # short query is what separates "this record is about what you asked"
        # from "this record happens to contain one of your words". Short queries
        # are exempt because a one-token query is usually an identifier.
        if len(tokens) >= cls.COVERAGE_MIN_TOKENS and matched_tokens < 2:
            total *= cls.SINGLE_MATCH_PENALTY

        return total

    @staticmethod
    def _match_variants(token: str) -> Tuple[str, ...]:
        """
        Variants of a query token used for matching, so that common
        BIDS plurals are treated as the same term:
        ``files -> (files, file)``, ``entities -> (entities, entity)``.
        """
        if token.endswith("s") and len(token) >= 4:
            return (token, token[:-1])
        return (token,)

    @staticmethod
    def _whole_word(token: str, text: str) -> bool:
        return re.search(rf"\b{re.escape(token)}\b", text) is not None

    @staticmethod
    def _prefix_word(token: str, text: str) -> bool:
        return re.search(rf"\b{re.escape(token)}[a-z0-9]*", text) is not None


# ====================================================================
# Formatter — record -> LLM-friendly text
# ====================================================================


class Formatter:
    """
    Formats a KnowledgeRecord into readable text for LLM consumption.

    Uses only fields that actually exist in the knowledge base schema.
    """

    RAW_CONTENT_LIMIT = 600

    @classmethod
    def format(
        cls,
        record: KnowledgeRecord,
        index: int,
        source_category: str = "",
    ) -> str:
        parts: List[str] = []
        parts.append(f"=== Knowledge Item {index} ===")
        parts.append(f"ID: {record.id}")
        parts.append(f"Type: {record.knowledge_type}")

        # Provenance (actual schema: source.file / section / key)
        src = record.source
        src_file = src.get("file", "")
        src_section = src.get("section", "")
        src_key = src.get("key", "")
        src_parts = [str(src_file)] if src_file else ["unknown"]
        if src_section:
            src_parts.append(f"section: {src_section}")
        if src_key:
            src_parts.append(f"key: {src_key}")
        parts.append(f"Source: {', '.join(src_parts)}")
        if source_category:
            parts.append(f"Source Category: {source_category}")
        if record.bids_version:
            parts.append(f"BIDS Version: {record.bids_version}")
        if record.schema_version:
            parts.append(f"Schema Version: {record.schema_version}")

        parts.append("")
        if record.title:
            parts.append(f"Title: {record.title}")
        if record.summary:
            parts.append(f"Summary: {record.summary}")
        if record.retrieval_text:
            parts.append(f"Description: {record.retrieval_text}")

        if record.requirements is not None:
            parts.append(f"Requirements: {cls._fmt(record.requirements)}")
        if record.conditions:
            parts.append(f"Conditions: {cls._fmt(record.conditions)}")
        if record.allowed_values:
            parts.append(f"Allowed Values: {cls._fmt(record.allowed_values)}")
        if record.expression:
            parts.append(f"Expression: {record.expression}")
        if record.severity:
            parts.append(f"Severity: {record.severity}")
        if record.unit:
            parts.append(f"Unit: {record.unit}")

        scope_text = cls._fmt_scope(record.scope)
        if scope_text:
            parts.append(f"Scope: {scope_text}")

        if record.raw_content:
            raw_str = json.dumps(record.raw_content, ensure_ascii=False)
            if len(raw_str) > cls.RAW_CONTENT_LIMIT:
                raw_str = raw_str[: cls.RAW_CONTENT_LIMIT] + "..."
            parts.append(f"Raw Content: {raw_str}")

        parts.extend(cls._fmt_enrichment(record.enrichment))

        parts.append("")
        return "\n".join(parts)

    @staticmethod
    def _fmt_enrichment(enrichment: Dict[str, Any]) -> List[str]:
        """Render the explanatory block, when the record has one.

        Labelled as explanation rather than specification so a model reading it
        does not quote it as though the standard said it. The resolution
        guidance is emitted last because it is what the user actually asked for.
        """
        if not enrichment:
            return []

        out: List[str] = ["", "--- Explanation (not normative specification text) ---"]

        for key, label in (
            ("description", "What this means"),
            ("interpretation", "How to read it"),
            ("why_it_matters", "Why it matters"),
        ):
            value = str(enrichment.get(key, "") or "").strip()
            if value:
                out.append(f"{label}: {value}")

        for key, label in (
            ("common_causes", "Common causes"),
            ("example_scenarios", "Examples"),
        ):
            values = enrichment.get(key)
            if isinstance(values, list) and values:
                out.append(f"{label}:")
                out.extend(f"  - {v}" for v in values if str(v).strip())

        guidance = str(enrichment.get("resolution_guidance", "") or "").strip()
        if guidance:
            out.append(f"How to resolve: {guidance}")

        notes = str(enrichment.get("additional_notes", "") or "").strip()
        if notes:
            out.append(f"Notes: {notes}")

        confidence = str(enrichment.get("confidence", "") or "").strip()
        if confidence:
            out.append(f"Explanation confidence: {confidence}")

        return out

    # -- value formatting -----------------------------------------------

    @staticmethod
    def _fmt(value: Any) -> str:
        if value is None:
            return ""
        if isinstance(value, str):
            return value
        if isinstance(value, list):
            return "; ".join(Formatter._fmt(v) for v in value)
        if isinstance(value, dict):
            return ", ".join(
                f"{k}: {Formatter._fmt(v)}" for k, v in value.items()
            )
        return str(value)

    @staticmethod
    def _fmt_scope(scope: Dict[str, Any]) -> str:
        if not scope:
            return ""
        bits: List[str] = []
        for key, value in sorted(scope.items()):
            if isinstance(value, list):
                items = [str(v) for v in value if v not in (None, "")]
                if items:
                    bits.append(f"{key}: {', '.join(items)}")
            elif value not in (None, ""):
                bits.append(f"{key}: {value}")
        return " | ".join(bits)


# ====================================================================
# Retriever — loads the KB once, answers repeated queries
# ====================================================================


class Retriever:
    """
    Loads the JSONL-based BIDS knowledge base and serves keyword queries.

    Parameters
    ----------
    data_dir : str
        Directory containing knowledge.jsonl (and optionally
        relationships.jsonl and sources.jsonl).
    """

    # How many neighbors to consider during relationship expansion.
    MAX_RELATED = 3

    def __init__(self, data_dir: str = "./") -> None:
        self.data_dir = Path(data_dir)

        self.records: List[KnowledgeRecord] = []
        self.blocks: List[List[Tuple[str, str, float]]] = []
        self.identities: List[str] = []
        self.edges: List[RelationshipEdge] = []
        self.source_categories: Dict[str, str] = {}

        # id -> record index (used to resolve relationship endpoints)
        self._index: Dict[str, int] = {}
        # validator issue code -> record index, for exact-code lookups
        self._code_index: Dict[str, int] = {}
        # metadata field / column name -> index of the record DEFINING it
        self._subject_index: Dict[str, int] = {}
        # term -> record indices containing it, and the same for short prefixes
        self._postings: Dict[str, Set[int]] = {}
        self._prefix_postings: Dict[str, Set[int]] = {}
        # adjacency: record_index -> [(relation, neighbor_index, direction)]
        self._adjacency: Dict[int, List[Tuple[str, int, str]]] = {}
        # term token -> inverse document frequency (computed over the KB)
        self._idf: Dict[str, float] = {}
        # adaptive minimum score for a result to be considered relevant
        self._min_best: float = MIN_BEST_SCORE

        self._load_knowledge()
        self._load_enrichment()
        self._load_relationships()
        self._load_sources()
        self._build_index()

    # -- Loading --------------------------------------------------------

    def _load_knowledge(self) -> None:
        path = self.data_dir / KNOWLEDGE_FILE
        if not path.exists():
            logger.warning("knowledge.jsonl not found at %s", path)
            return

        loaded, skipped = 0, 0
        try:
            with open(path, "r", encoding="utf-8") as f:
                for line_no, line in enumerate(f, 1):
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        data = json.loads(line)
                        if not isinstance(data, dict) or not data.get("id"):
                            raise ValueError("record has no 'id' field")
                        self.records.append(KnowledgeRecord(data))
                        loaded += 1
                    except (json.JSONDecodeError, ValueError) as exc:
                        skipped += 1
                        logger.warning(
                            "Skipping malformed line %d of %s: %s",
                            line_no, path.name, exc,
                        )
        except (OSError, UnicodeDecodeError) as exc:
            logger.error("Failed to read %s: %s", path, exc)
            self.records.clear()
            return

        logger.info("Loaded %d records (%d skipped) from %s", loaded, skipped, path.name)

    def _load_enrichment(self) -> None:
        """Merge ``enriched_knowledge.jsonl`` onto the records already loaded.

        Only the ``ai_enrichment`` block is taken. The base record stays
        authoritative for everything else, so an enrichment file generated
        against an older extraction cannot overwrite a corrected rule, it can
        only fail to have an entry for it.
        """
        path = self.data_dir / ENRICHED_FILE
        if not path.exists():
            logger.info("%s not found; serving un-enriched records.", ENRICHED_FILE)
            return

        by_id = {record.id: record for record in self.records}
        merged, orphaned = 0, 0

        for line_no, line in enumerate(self._read_lines(path), 1):
            try:
                data = json.loads(line)
            except json.JSONDecodeError:
                logger.warning("Skipping malformed line %d of %s", line_no, path.name)
                continue

            if not isinstance(data, dict):
                continue

            enrichment = data.get("ai_enrichment")
            if not isinstance(enrichment, dict) or not enrichment:
                continue

            target = by_id.get(str(data.get("id", "")))
            if target is None:
                orphaned += 1
                continue

            target.enrichment = enrichment
            merged += 1

        if orphaned:
            logger.info(
                "%d enrichment record(s) refer to ids that no longer exist; "
                "re-run the enrichment pass to cover the current knowledge base.",
                orphaned,
            )
        logger.info("Merged %d enrichment record(s) from %s", merged, path.name)

    def _load_relationships(self) -> None:
        path = self.data_dir / RELATIONSHIPS_FILE
        if not path.exists():
            logger.info("relationships.jsonl not found; relationship expansion disabled.")
            return
        for line_no, line in enumerate(self._read_lines(path), 1):
            try:
                data = json.loads(line)
                if isinstance(data, dict) and data.get("source") and data.get("target"):
                    self.edges.append(RelationshipEdge(data))
            except json.JSONDecodeError:
                logger.warning("Skipping malformed relationship line %d of %s", line_no, path.name)
        logger.info("Loaded %d relationships from %s", len(self.edges), path.name)

    def _load_sources(self) -> None:
        """Load sources.jsonl into a normalized source_path -> category map."""
        path = self.data_dir / SOURCES_FILE
        if not path.exists():
            return
        for line_no, line in enumerate(self._read_lines(path), 1):
            try:
                data = json.loads(line)
                sp = data.get("source_path", "")
                if sp and data.get("category"):
                    self.source_categories[sp.replace("\\", "/")] = str(data["category"])
            except json.JSONDecodeError:
                logger.warning("Skipping malformed source line %d of %s", line_no, path.name)

    @staticmethod
    def _read_lines(path: Path) -> List[str]:
        try:
            with open(path, "r", encoding="utf-8") as f:
                return [ln.strip() for ln in f if ln.strip()]
        except (OSError, UnicodeDecodeError) as exc:
            logger.error("Failed to read %s: %s", path, exc)
            return []

    # -- Indexing -------------------------------------------------------

    def _build_index(self) -> None:
        self.blocks = [r.build_search_blocks() for r in self.records]
        self.identities = [r.identity_text() for r in self.records]
        self._index = {r.id: i for i, r in enumerate(self.records)}

        # Validator issue codes, indexed exactly.
        #
        # A user asking about a failed validation pastes the code the validator
        # printed and nothing else. Token scoring handles that badly, because a
        # code splits into ordinary words that occur throughout the knowledge
        # base: TSV_COLUMN_MISSING becomes "tsv", "column", "missing", which
        # every tabular record contains. The result is a confident answer about
        # the wrong rule, which is worse than no answer. An exact map makes the
        # one query that matters most deterministic.
        for i, record in enumerate(self.records):
            code = (record.scope or {}).get("issue_code")
            if isinstance(code, str) and code:
                self._code_index.setdefault(code.strip().upper(), i)

        # Metadata fields and TSV columns, indexed by the name they are written
        # under, pointing at the record that DEFINES them.
        #
        # Naming a field is the other half of naming an issue code, and it fails
        # the same way. "What does EffectiveEchoSpacing mean" is one token, and
        # the validation checks that mention the field score above the field's
        # own definition simply by repeating the word in more places. The
        # definition is the direct answer to a question that names a field, so it
        # is looked up rather than competed for.
        for i, record in enumerate(self.records):
            source_file = str((record.source or {}).get("file", ""))
            if source_file not in ("objects/metadata.yaml", "objects/columns.yaml"):
                continue
            scope = record.scope or {}
            names = list(scope.get("metadata_fields") or []) + list(scope.get("columns") or [])
            for name in names:
                if not isinstance(name, str) or not self._is_distinctive(name):
                    continue
                self._subject_index.setdefault(name.lower(), i)
                # Also under the form with separators removed, so a query that
                # writes participant_id and one that writes participantid both
                # resolve.
                self._subject_index.setdefault(re.sub(r"[^a-z0-9]", "", name.lower()), i)

        # Adjacency over edges whose BOTH endpoints resolve to records.
        # (Many relationship nodes are group placeholders that are not
        # themselves knowledge records; those edges are skipped.)
        for edge in self.edges:
            s_idx = self._index.get(edge.source)
            t_idx = self._index.get(edge.target)
            if s_idx is None or t_idx is None:
                continue
            self._adjacency.setdefault(s_idx, []).append((edge.relation, t_idx, "out"))
            self._adjacency.setdefault(t_idx, []).append((edge.relation, s_idx, "in"))

        # IDF map: common boilerplate terms (must/should/field/...) are
        # damped so that specific technical terms dominate the ranking.
        #
        # The same pass builds the postings lists. Scoring every record against
        # every query is linear in the size of the knowledge base, which is the
        # one real cost of holding more records: a query that can only match a
        # few dozen records was paying to be compared against all of them.
        # Postings narrow the candidates to records that contain at least one
        # query term, which is exactly the set that can score above zero.
        word_re = re.compile(r"[a-z0-9]+")
        df = Counter()
        for idx, blocks in enumerate(self.blocks):
            seen = set()
            for _label, text, _weight in blocks:
                seen.update(t for t in word_re.findall(text) if t not in Scorer.STOPWORDS)
            df.update(seen)
            for term in seen:
                self._postings.setdefault(term, set()).add(idx)
                # A short prefix of every term as well, because a query token
                # that is not a whole word can still match as a word PREFIX
                # (three characters or more). Without these entries the prefix
                # rule would silently stop firing, changing results rather than
                # only making them faster.
                if len(term) >= Scorer.MIN_PREFIX_LEN:
                    self._prefix_postings.setdefault(
                        term[:Scorer.MIN_PREFIX_LEN], set()
                    ).add(idx)
        n = max(len(self.records), 1)
        self._idf = {
            token: max(0.2, math.log((n + 1) / (count + 1)))
            for token, count in df.items()
        }
        self._min_best = min(MIN_BEST_SCORE, max(0.5, n * 0.005))

        logger.info("Built index: %d records, %d resolvable adjacency entries",
                    len(self.records), sum(len(v) for v in self._adjacency.values()))

    # -- Retrieval ------------------------------------------------------

    def retrieve(self, query: str, top_k: int = 2) -> str:
        """Return the ``top_k`` most relevant knowledge items as a string."""
        if not self.records:
            return MSG_EMPTY_KB if self._knowledge_file_exists() else MSG_NO_KB.format(self.data_dir)

        if not query or not query.strip():
            return MSG_EMPTY_QUERY

        # 1. Score every record.
        scored = self._score_all(query)

        # 2. Any validator issue code named in the query outranks the scorer.
        code_hits = self._codes_in(query)

        if not code_hits and (not scored or scored[0][0] < self._min_best):
            return MSG_NO_MATCH.format(query)

        # 3. Combine base hits with relationship-aware neighbours.
        combined = self._expand_related(query, scored) if scored else []

        # 4. Exact lookups are placed above everything the scorer produced.
        #
        # Codes come first: a user quoting a code is asking about that specific
        # finding. Field and column definitions come next, and only when the
        # scorer already rates them as relevant, so that "what causes X to be
        # rejected" still reaches the checks about X rather than being displaced
        # by X's definition.
        subject_hits = [
            idx for idx in self._subjects_in(query)
            if idx not in code_hits and any(idx == i for _s, i in scored)
        ]

        top = (combined[0][0] if combined else 0.0) + 100.0
        promoted = (
            [(top - rank, idx) for rank, idx in enumerate(code_hits)]
            + [(top - len(code_hits) - rank - 0.5, idx)
               for rank, idx in enumerate(subject_hits)]
        )
        combined = promoted + combined

        combined.sort(key=lambda x: x[0], reverse=True)

        # 3. Select top_k (deduplicated, stable order).
        selected: List[Tuple[float, int]] = []
        seen: Set[int] = set()
        for score, idx in combined:
            if idx in seen:
                continue
            seen.add(idx)
            selected.append((score, idx))
            if len(selected) >= top_k:
                break

        # 4. Format for the LLM.
        chunks = []
        for rank, (_score, idx) in enumerate(selected, 1):
            record = self.records[idx]
            category = self.source_categories.get(
                str(record.source.get("file", "")).replace("\\", "/"), ""
            )
            chunks.append(Formatter.format(record, rank, category))

        return "\n".join(chunks)

    # -- Exact issue-code lookup ----------------------------------------

    # A validator issue code is an identifier of at least two underscore-joined
    # segments. Most are upper case, but not all: the schema defines
    # M0Type_SET_INCORRECTLY, whose first segment is mixed case. An upper-case
    # only pattern silently skipped those codes, and the fallback then ranked
    # the longer codes that share their prefix above the code actually asked
    # about. Mixed case is therefore accepted, which also matches ordinary
    # snake_case words; those are simply misses against the code index, since it
    # holds nothing but real codes.
    _CODE_RE = re.compile(r"\b[A-Za-z][A-Za-z0-9]*(?:_[A-Za-z0-9]+)+\b")

    def _codes_in(self, query: str) -> List[int]:
        """Record indices for every validator issue code named in the query."""
        hits: List[int] = []
        for token in self._CODE_RE.findall(query):
            # The index is keyed upper case, so a mixed-case code such as
            # M0Type_SET_INCORRECTLY resolves however the user typed it.
            idx = self._code_index.get(token.upper())
            if idx is not None and idx not in hits:
                hits.append(idx)
        return hits

    # Identifier-shaped words, keeping underscores so participant_id survives.
    _SUBJECT_RE = re.compile(r"[A-Za-z][A-Za-z0-9_]{2,}")

    @staticmethod
    def _is_distinctive(name: str) -> bool:
        """Whether a field or column name is unambiguous enough to look up.

        Some BIDS names are ordinary English words: there are fields called
        Type, Name, Columns, Description and Units. Promoting a record because a
        sentence happened to contain "columns" answers a question about
        participants.tsv with the definition of a field called Columns. A name
        earns a direct lookup only when writing it is unlikely to be accidental,
        which means an underscore or an internal capital. Everything else is
        still reachable through ordinary scoring, which weighs it against the
        rest of the query instead of overriding it.
        """
        if not name or len(name) < 4:
            return False
        if "_" in name:
            return True
        return any(c.isupper() for c in name[1:])

    def _subjects_in(self, query: str) -> List[int]:
        """Record indices for every metadata field or column named in the query."""
        hits: List[int] = []
        for token in self._SUBJECT_RE.findall(query):
            lowered = token.lower()
            for candidate in (lowered, re.sub(r"[^a-z0-9]", "", lowered)):
                idx = self._subject_index.get(candidate)
                if idx is not None and idx not in hits:
                    hits.append(idx)
                    break
        return hits

    def lookup_code(self, code: str) -> Optional[str]:
        """Return the formatted record for one validator issue code.

        Exposed for callers that already know the code, such as an agent
        explaining a specific line of validator output.
        """
        idx = self._code_index.get(str(code or "").strip().upper())
        if idx is None:
            return None
        record = self.records[idx]
        category = self.source_categories.get(
            str(record.source.get("file", "")).replace("\\", "/"), ""
        )
        return Formatter.format(record, 1, category)

    def known_codes(self) -> List[str]:
        """Every validator issue code the knowledge base can explain."""
        return sorted(self._code_index)

    # -- Scoring internals ----------------------------------------------

    def _candidates(self, query: str) -> Set[int]:
        """Records that contain at least one query term, exactly or as a prefix.

        A record sharing no term with the query scores zero, so restricting
        scoring to this set is a speed-up and not a change in behaviour.
        """
        candidates: Set[int] = set()
        for token in Scorer.tokenize(query):
            for variant in Scorer._match_variants(token):
                candidates |= self._postings.get(variant, frozenset())
            if len(token) >= Scorer.MIN_PREFIX_LEN:
                candidates |= self._prefix_postings.get(
                    token[:Scorer.MIN_PREFIX_LEN], frozenset()
                )
        return candidates

    def _score_all(self, query: str) -> List[Tuple[float, int]]:
        scored: List[Tuple[float, int]] = []
        for idx in self._candidates(query):
            s = Scorer.score(
                query, self.records[idx], self.blocks[idx],
                self.identities[idx], self._idf,
            )
            if s > 0:
                scored.append((s, idx))
        # Sorted by score, then by record index so that equal scores come back
        # in a stable order rather than in whatever order the set iterated.
        scored.sort(key=lambda x: (-x[0], x[1]))
        return scored

    def _expand_related(
        self, query: str, scored: List[Tuple[float, int]]
    ) -> List[Tuple[float, int]]:
        """
        Relationship-aware enrichment.

        For the top results, follow relationships.jsonl edges to neighbours
        and add a small bonus to neighbours that are themselves relevant to
        the query (their own score > 0). This keeps results query-focused:
        an edge alone never pulls in an unrelated record, and the entire
        relationship file is never returned.
        """
        if not self.edges or not scored:
            return list(scored)

        best_score = scored[0][0]
        additions: Dict[int, float] = {}

        for score, idx in scored[: self.MAX_RELATED]:
            for _relation, neighbor_idx, _direction in self._adjacency.get(idx, ()):
                if neighbor_idx in additions:
                    continue
                n_score = Scorer.score(
                    query,
                    self.records[neighbor_idx],
                    self.blocks[neighbor_idx],
                    self.identities[neighbor_idx],
                    self._idf,
                )
                if n_score <= 0:
                    continue
                # Neighbours of the top result get a small nudge.
                bonus = 1.0 if score >= 0.5 * best_score else 0.25
                additions[neighbor_idx] = n_score + bonus

        combined: List[Tuple[float, int]] = list(scored)
        combined.extend((s, i) for i, s in additions.items())
        combined.sort(key=lambda x: x[0], reverse=True)
        return combined

    def _knowledge_file_exists(self) -> bool:
        return (self.data_dir / KNOWLEDGE_FILE).exists()

    # -- Introspection (kept for compatibility) -------------------------

    def get_record_count(self) -> int:
        return len(self.records)

    def get_record_types(self) -> Dict[str, int]:
        counts: Dict[str, int] = {}
        for rec in self.records:
            counts[rec.knowledge_type] = counts.get(rec.knowledge_type, 0) + 1
        return counts


# ====================================================================
# Standalone demo
# ====================================================================

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    kb_dir = Path(__file__).parent
    retriever = Retriever(str(kb_dir))

    print(f"Loaded {retriever.get_record_count()} records")
    print(f"Types: {retriever.get_record_types()}")
    print("=" * 70)

    queries = [
        "What is the HEDVersion field used for?",
        # "What is the task entity?",
        # "What are the requirements for a BOLD file?",
        # "Why is sub-01_task-rest_bold.nii.gz valid or invalid?",
        # "What files are required for a BIDS dataset?",
        # "What metadata is required for EEG recordings?",
        # "What is the difference between task and run entities?",
    ]

    for q in queries:
        print(f"\n>>> Query: {q}")
        print("-" * 60)
        print(retriever.retrieve(q, top_k=3))
        print("=" * 70)
